### ISSUE TITLE
Diskussion: Impressum erstellen oder nicht

### ISSUE THREAD

**Issue by troppes** [Nomi-1/M3_Study#12]
Falls ja, dann verweis auf die Gebühren

Ansonsten im Fragebogen prüfen, ob die Leute das gesucht haben.

**Comment by Sabrows** [comment]
Wie siehts aus mit den Social Media Links? Die führen ins Nichts bzw. zu errors

**Comment by troppes** [comment]
> Wie siehts aus mit den Social Media Links? Die führen ins Nichts bzw. zu errors
Die sollte am besten einfach auf # verlinken oder?

**Comment by Nomi-1** [comment]
kümmere mich darum - lege ein issue an
