### ISSUE TITLE
Headlines & Beschreibungen der Umfragen anpassen

### ISSUE THREAD

**Issue by Nomi-1** [Nomi-1/M3_Study#14]

**Comment by Sabrows** [comment]
Hab die Fragebögen aktualisiert:

 - [Pre](https://docs.google.com/forms/d/1pXi1HyNRp8LXgOf9z6W16imgDrSCsUQJugx8dKhSfPQ/edit)
 - [Mid](https://docs.google.com/forms/d/108C7adNxwxQoIecgskVrdSGba4BYx-x2d40cBHJpiKg/edit)
 - [Post](https://docs.google.com/forms/d/1Hl7mPcdlPffvNj8LmOItkGFIHhMJK6EMuS-AvPHIqls/edit)
